close: #16
atsushimemet/vook_web_v3 pull request #17
Opened 2023-04-21 22:49 UTC by garammasala29

2023-04-23 11:46 UTC, garammasala29 commented
@atsushimemet 
ご確認よろしくお願いします。

2023-04-24 15:32 UTC, atsushimemet requested changes
@garammasala29 
CI環境の構築とそれに紐づく修正ありがとう!

下記観点から、CI環境の構築とそれに紐づく修正は区別したほうがいいと思ってます。
- イシューをベースに開発している。
  - 今回のPRに紐づくイシューはCI環境の構築 #16
  - なのでこのPRに含まれる変更は下記が望ましいと考えている。
    - CI関連の設定ファイル 
      - 静的コード解析ツールの設定ファイル
      - 自動整形ツールの設定ファイル
    - CI関連のパッケージの依存関係の更新
    - CIのyaml

なので、CIを実施した結果の修正箇所は別途イシューを立てて、それ用にPRを立ててもらえるといいかなと思ってます。

上記のように考えているので、意図がなければPRの分割をお願いします。
（あれば是非教えてください!）

2023-04-24 15:33 UTC, atsushimemet commented
@garammasala29 
ご確認よろしくお願いします。

2023-04-24 17:40 UTC, garammasala29 commented
@atsushimemet 
了解しました。以下、教えてください。
- CIのテストが落ちたままPR、mergeとしても問題ないという認識で合ってますか？
（ここに違和感があったので今回は全て修正していました）
- 別issueに切り出すとなると、今回のcommitでは「ーの指摘箇所を修正」を除けばいいと思うんですが、これをするためのベストなgit操作はありますか？
`revert`や`reset`でコミットを取り消す方法は知っていますが、取り消したコミットを保持する方法や別ブランチに切り出す方法があれば知りたいです。

2023-04-25 12:35 UTC, merged

2023-04-25 12:40 UTC, atsushimemet commented
@garammasala29 
こちらに関してはデプロイ不要な認識です。